module.exports.descriptors = [
    'Appetizing', 
    'Scrumptious',
    'Yummy', 
    'Juicy', 
    'Succulent', 
    'Heavenly', 
    'Palatable', 
    'Saporous',
    'Tempting',
    'Average',
    'Toothsome',
    'Poor',
    'Bad',
    'Unhygienic',
    'Inedible'

]

module.exports.suffix= [
    'Lunch',
    'Brunch',
    'Breakfast',
    'Dinner',
    'Baked Goods',
    'Indian Food',
    'Affair of Taste',
    'food',
    'Meal',
    'for the Taste Buds',
    'bites of food',
    'Morsels',
    'Pastries',
    'Breads',
    'Noodles',
    'Drinks',
    'Experience',
    '! :Redefining dining?'
]

module.exports.restaurants=[
    "	Parallel 37	"	,
    "	Starbelly	"	,
    "	Brass Tacks	"	,
    "	Lord Stanley	"	,
    "	Top of the Mark	"	,
    "	Pier 23	"	,
    "	Plumed Horse	"	,
    "	Everest	"	,
    "	The Aviary	"	,
    "	Blue Plate	"	,
    "	Bones	"	,
    "	Burger & Beer Joint	"	,
    "	Catch of the Day	"	,
    "	CRUST	"	,
    "	Daily Grill	"	,
    "	Full Moon	"	,
    "	Garage Kitchen + Bar	"	,
    "	Grubstake	"	,
    "	Harvest Beat	"	,
    "	Nin Com Soup	"	,
    "	Ozone	"	,
    "	Rooftoop at E11EVEN	"	,
    "	Skillet Counter	"	,
    "	Stoneburner	"	,
    "	Street Taco	"	,
    "	The Egg & Us	"	,
    "	The Incredible Cafe	"	,
    "	The River Seafood	"	,
    "	Townsend	"	,
    
]
